### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by HelloFriend001** [ice987987/ioBroker.husqvarna-automower#33]
### The problem

I still get the error message:

husqvarna-automower.0 | 2022-06-12 10:02:40.101 | error | Error: "Automower Connect API" not reachable. (ERR_#004)
husqvarna-automower.0 | 2022-06-12 10:02:39.847 | info | starting adapter "husqvarna-automower"...
husqvarna-automower.0 | 2022-06-12 10:02:39.809 | info | starting. Version 0.1.0 (non-npm: ice987987/ioBroker.husqvarna-automower#69f868487c91c4757aadb309e50ec28c5f7b0e98) in /opt/iobroker/node_modules/iobroker.husqvarna-automower, node: v14.19.3, js-controller: 4.0.23

I have set up the husqvarna account several times. I doesn't help.
**Besides, the link in the README "Please make sure that you have created an account, password and API-Key according to **[these instructions](https://developer.husqvarnagroup.cloud/docs/getting-started).** "Old" logins will not work."
is not working.**

### Version of nodejs

14.19.3

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

0.1.0

### Operating system incl. version running ioBroker

Linux 

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

<html>
<body>

husqvarna-automower.0 | 2022-06-12 10:02:40.101 | error | Error: "Automower Connect API" not reachable. (ERR_#004)
-- | -- | -- | --
husqvarna-automower.0 | 2022-06-12 10:02:39.847 | info | starting adapter "husqvarna-automower"...
husqvarna-automower.0 | 2022-06-12 10:02:39.809 | info | starting. Version 0.1.0 (non-npm: ice987987/ioBroker.husqvarna-automower#69f868487c91c4757aadb309e50ec28c5f7b0e98) in /opt/iobroker/node_modules/iobroker.husqvarna-automower, node: v14.19.3, js-controller: 4.0.23

</body>
</html>

**Comment by ice987987** [comment]
Husqvarna changed their homepage a few days ago, therefore one link was no longer active, which is now fixed.

ERR_#004 means, that the adapter is not able to connect to husqvarna with your generated KEY, PASSWORD and USERNAME, which is the first task in the programm. If you put the adapter in "debug mode" your credentials are visible in the log. Are they correct?

if you still get an error: please delete the application on the husqvarna homepage, wait a few hours and try again.

did you connect an application to your api?

**Comment by HelloFriend001** [comment]
Thanks for your quick response. I checked credentials - they are ok. I have waited 6 hours after deleting all aplication and tried again. I created new application with an Authentication API and an Automower Connect API. However, error remains the same:

<html>
<body>


husqvarna-automower.0 | 2022-06-12 19:54:16.121 | error | Error: "Automower Connect API" not reachable. (ERR_#004)
-- | -- | -- | --
husqvarna-automower.0 | 2022-06-12 19:54:16.120 | debug | [getAccessToken]: error.config: {"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/0.27.2","Content-Length":114},"method":"post","url":"https://api.authentication.husqvarnagroup.dev/v1/oauth2/token","data":"grant_type=password&client_id=8498d6df-34a7-49ad-b384-f1cc78958ad6&username=aaa.bbb@online.de&password=Ln142+Ki110"}
husqvarna-automower.0 | 2022-06-12 19:54:16.119 | debug | [getAccessToken]: HTTP status response: 400; headers: {"content-type":"application/json; charset=utf-8","content-length":"133","connection":"close","date":"Sun, 12 Jun 2022 17:54:16 GMT","x-amzn-requestid":"71782ebe-2f69-401d-afb6-8f3c5b4d5427","x-dns-prefetch-control":"off","referrer-policy":"no-referrer","x-permitted-cross-domain-policies":"none","x-xss-protection":"0","access-control-allow-origin":"*","expect-ct":"max-age=0","surrogate-control":"no-store","strict-transport-security":"max-age=15552000; includeSubDomains","x-amzn-remapped-content-length":"133","x-frame-options":"SAMEORIGIN","access-control-allow-headers":"Origin,X-Requested-With,X-Internal-Request-Id,X-External-Request-Id,Content-Type,Accept,X-IAM-Session,Authorization,Authorization-Provider","x-amzn-remapped-connection":"keep-alive","x-amz-apigw-id":"Tns7SEjqjoEFu9Q=","cache-control":"no-store, no-cache, must-revalidate, proxy-revalidate","expires":"0","x-internal-request-id":"62010663","x-content-type-options":"nosniff","etag":"W/\"85-2ouRw9IhRoeXbHmMlGCm2e5yiws\"","access-control-allow-methods":"GET, POST, OPTIONS, PUT, PATCH, DELETE","pragma":"no-cache","x-amzn-remapped-date":"Sun, 12 Jun 2022 17:54:16 GMT","x-cache":"Error from cloudfront","via":"1.1 c00313a056e59f376cf028f05a0244e4.cloudfront.net (CloudFront)","x-amz-cf-pop":"HAM50-C3","x-amz-cf-id":"KD0VIUjamU8VJzi15rGj-h-13XTjpP8QLzSRiyZTS6p45xfMyoJcyw=="}; data: {"error":"unauthorized_client","error_description":"Unauthorized client: `grant_type` is invalid","error_code":"unauthorized.client"}
husqvarna-automower.0 | 2022-06-12 19:54:15.912 | debug | The configuration has been checked successfully. Trying to connect "Automower Connect API"...


</body>
</html>

Do you have any idea?

**Comment by ice987987** [comment]
did you connect the husqvarna application to your api?

**Comment by HelloFriend001** [comment]
I am not sure what you mean!? 
I connected my Husqvarna Automower to my Husquarna account and can stear it from my apps in IOS and/or Android. So the connection to my account works.

**Comment by ice987987** [comment]
It looks like husqvarna did not only change the homepage. There might also be changes in the login procedure.

Do you want to login to the first time now or did you already had a connection with this adapter?

**Comment by TomBo1969** [comment]
Same problem here..
First time installation of the adapter, installation requirements are fullfilled, credentials are correct, in the Husqvarna Developer Portal my application ist connected to the new API but: Error: "Automower Connect API" not reachable. (ERR_#004)

**Comment by HelloFriend001** [comment]
> It looks like husqvarna did not only change the homepage. There might also be changes in the login procedure.
> 
> Do you want to login to the first time now or did you already had a connection with this adapter?

With this adapter I want to log in for the first time.

**Comment by ice987987** [comment]
there is a new beta version available with the "new login-procedure" from husqvarna. If you want, you could try it with the following link:
https://github.com/ice987987/ioBroker.husqvarna-automower/tree/development

(under NPM6, the installation takes a while, due to the [NPM6-Bug](https://forum.iobroker.net/topic/55183/github-installationen-mit-npm6-sehr-langsam))

**Comment by HelloFriend001** [comment]
> there is a new beta version available with the "new login-procedure" from husqvarna. If you want, you could try it with the following link: https://github.com/ice987987/ioBroker.husqvarna-automower/tree/development
> 
> (under NPM6, the installation takes a while, due to the [NPM6-Bug](https://forum.iobroker.net/topic/55183/github-installationen-mit-npm6-sehr-langsam))

Thanks @ice987987  
Top Job - it's working !!! 
Connected now to API and Mower.

**Comment by ice987987** [comment]
@TomBo1969 
What is your experience with the updated adapter?

**Comment by TomBo1969** [comment]
@ice987987 It works!!
Thanks a lot!
